# Generated by Django 5.1.4 on 2024-12-13 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0002_alter_article_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('album_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('img_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='single_images/img')),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_site.album')),
            ],
        ),
    ]
