# Generated by Django 5.1.4 on 2024-12-13 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0003_album_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='album_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_site.categories'),
        ),
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Album',
        ),
    ]
