# Generated by Django 5.1.4 on 2024-12-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site', '0004_alter_image_album_id_image_name_delete_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('ad_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='advertisement_images/img')),
            ],
        ),
    ]
